### PR TITLE
Add long string option type to config file.

### LINKED ISSUE #14: Long string option type
Just like `short-string`, but it's got a `<textarea>` interface instead of `<input type="text" />`.

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
Add text area to config file

Fixes #14

### CODE REVIEW

**Comment by haydn** [comment]
On my phone, so I haven’t been able to look at this properly, but I think I’ve steered you wrong with the original issue’s description.

Currently there isn’t any code handling `long-string` as an input type for options.

I can’t quite remember what I wrote, but there’ll be some whacky code somewhere towards the bottom of the `Editor.js` file that handles `short-string`… probably a `switch` statement inside a `map()`. That needs another case added to it for handling `long-string` input types.

Does that make sense? I’ll link you to the relevant parts when I’m in front of a computer again.

**Comment by Mxchaeltrxn** [comment]
Yeah I remember seeing that section. Is it the section that starts at around line 1260 in Editor.js? I didn't see any components with "long-string" as its input so I don't fully understand what it is used for. Another way to ask the question would be "how is long-string supposed to be different to short-string"?

**Comment by haydn** [comment]
@Mxchaeltrxn Yep, you're on it. Line 1260 is where the "magic" happens:

https://github.com/haydn/sketchbook/blob/master/src/Editor.js#L1260-L1304

That's what renders this UI:

image

Currently, `short-string` is the only type of input that an option can be configured with, but the plan is to have a bunch of different inputs a developer can use.

The `long-string` input would be better for configuring options with lots of text. For example, the current `Paragraph` component would be easier to use if it was using a `long-string` input type instead of a `short-string`. The `Textarea` component you've added is another great example. However, the `Textarea` component you've added can't have it's text changed using the options panel at the moment because it's input type (`long-string`) isn't handled in the `switch` statement:

image

Instead of rendering anything it's falling back to the useless `return null;` default case:

https://github.com/haydn/sketchbook/blob/master/src/Editor.js#L1304-L1305

Ideally, the default case would through an error instead of failing silently.

**Comment by Mxchaeltrxn** [comment]
I see. I'll get started on that again tomorrow

**Comment by Mxchaeltrxn** [comment]
I've updated the code but wasn't really sure how to style the text area so I've chosen something simple for now

**Comment by haydn** [comment]
:+1: Looks good for now. We can polish the UI later. Thanks!

**Pull request merged**
