### PR TITLE
Update keyCode to code values

### LINKED ISSUE #33: Replace `keyCode` usages with `key`
The `keyCode` property has been deprecated:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Instead, we should use `code`:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

### PR DESCRIPTION
**Pull request by Mxchaeltrxn**
Addressing issue #33.

Edit: This isn't done yet. I missed some values.

Fixes #33.

### CODE REVIEW

**Comment by haydn** [comment]
@Mxchaeltrxn Thanks for tackling this one! If it helps, the spot where `keyCode` is introduced is in the `useKeys.js` file:

- https://github.com/haydn/sketchbook/blob/master/src/useKeys.js#L17
- https://github.com/haydn/sketchbook/blob/master/src/useKeys.js#L28

This is then imported into the `Editor.js` where your changes will take effect.

**Comment by haydn** [comment]
@Mxchaeltrxn Is this ready to go now? I haven’t had a chance to test it out on my computer yet, but at a glance the code changes look good. 👍

**Comment by Mxchaeltrxn** [comment]
@haydn I manually tested it yesterday and it seemed to work. 

I don't know if backspace is a good hotkey option though since it can make the user go back a page?

**Comment by haydn** [comment]
Sweet. I’ll take a look when I get a chance and have a play.

Ah! Good catch. Might need to add a `preventDefault()` to stop that happening.

**Pull request merged**
